sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
env:
  global:
    - COVERAGE=1 SKIP_POD_LINKCHECK=1
matrix:
  allow_failures:
    - perl: '5.8'
before_install:
  - cpanp x
  - eval $(curl https://travis-perl.github.io/init) --auto
